### ISSUE TITLE
Have you tried LODS in zero123 guidance?

### ISSUE THREAD

**Issue by flyingdoubleG** [yangxiaofeng/LODS#1]
![image](https://github.com/yangxiaofeng/LODS/assets/53119724/378ce94c-5c07-4b75-9fce-d51122948888)
I wonder if authors tried LODS in zero123 guidance before and will it work?

**Comment by yangxiaofeng** [comment]
Hi, thank you for your interest in our work.
We tried 0123 + lods, 0123 + vsd, 0123 + sds. It feels to us that lods and vsd only provide marginal improvements on 0123 compared with sds. 

One possible reason is that the learning process of 0123 on Objaverse might cause the model to lose finer details in the textures of objects. Therefore, lods and vsd can not learn to recover those details. 

Another reason might be lods is learning to reduce the guidance scale during the learning process. Therefore, if the guidance scale starts from large values (e.g. 100 in sd), there is lots of room for improvement. If the guidance scale starts from small values (e.g. 10 in 0123), there might not be much room for improvement.
