### ISSUE TITLE
Some problems about optimizer.

### ISSUE THREAD

**Issue by zcai0612** [yangxiaofeng/LODS#2]
Thanks for your brilliant work!
I found in the application of GaussanDreamer-based LODS. The learnable text embeddings are not included in the optimizer of torch lightning in the function `configure_optimizers()`. Hope for your response, I am not sure about that : )

**Comment by yangxiaofeng** [comment]
Hi zcai,

Thank you very much for the bug report! We committed a fix to the issue. Now it should work.
